// Markdown export for the Intelligence Report. Pure and unit-testable: it
// derives the session numbers from the advisor store exactly like the
// rendered report does, reusing the same business utils (loan calculators,
// red-flag engine) so the file can never disagree with the math.
import { monthlyPayment, totalCost } from '@/utils/financeCalculators';
import { docFeeFlags, addOnFlags } from '@/utils/redFlags';
import type { AdvisorState } from '@/hooks/useAdvisorState';

function parseNumber(value: unknown): number {
  const n = Number(value);
  return typeof n === 'number' && Number.isFinite(n) ? n : 0;
}

function usd(value: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(Math.round(value));
}

function str(state: Record<string, unknown> | undefined, key: string): string {
  const v = state?.[key];
  return typeof v === 'string' ? v : '';
}

function rec(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : undefined;
}

const NEED_LABELS: Record<string, string> = {
  awd: 'All-wheel drive',
  seating5plus: '5+ seats',
  highFuelEconomy: '30+ MPG combined',
  topSafetyPick: 'IIHS Top Safety Pick+',
  appleCarPlay: 'Apple CarPlay',
  androidAuto: 'Android Auto',
};

const NOT_COMPLETED = (step: string) => `> Step ${step} not completed yet.`;

export function reportFileName(savedAt: string | null | undefined): string {
  const day = (savedAt ?? new Date().toISOString()).slice(0, 10);
  return `car-purchase-intelligence-report-${day}.md`;
}

export function buildReportMarkdown(
  advisor: AdvisorState | null | undefined,
  savedAt: string | null | undefined,
): string {
  const s = rec(advisor);
  const lines: string[] = [];

  lines.push('# Car Purchase Intelligence Report');
  lines.push('');
  lines.push(`_Generated by Buy Smart with Larry · ${savedAt ? new Date(savedAt).toLocaleString() : new Date().toLocaleString()}_`);
  lines.push('');
  lines.push('> Educational guidance based on the numbers you entered — not financial advice.');
  lines.push('');

  // Budget (Step 1)
  lines.push('## Your budget');
  const intake = rec(s?.intake);
  const budget = parseNumber(intake?.monthlyBudget);
  if (budget > 0) {
    lines.push(`- Monthly budget: ${usd(budget)}`);
    if (parseNumber(intake?.downPayment) > 0) lines.push(`- Down payment: ${usd(parseNumber(intake?.downPayment))}`);
    if (str(intake, 'creditRange')) lines.push(`- Credit range: ${str(intake, 'creditRange')}`);
  } else {
    lines.push(NOT_COMPLETED('1'));
  }
  lines.push('');

  // Financing (Step 3)
  lines.push('## Financing math');
  const finance = rec(s?.finance);
  const hasFinance = !!finance && str(finance, 'vehiclePrice').trim() !== '';
  if (hasFinance) {
    const price = parseNumber(finance?.vehiclePrice);
    const down = parseNumber(finance?.downPayment);
    const apr = parseNumber(finance?.apr);
    const term = parseNumber(finance?.termMonths);
    const principal = Math.max(0, price - down);
    const payment = monthlyPayment(principal, apr, term);
    lines.push(`- Vehicle price: ${usd(price)}`);
    lines.push(`- Amount financed: ${usd(principal)}`);
    lines.push(`- APR / term: ${apr}% / ${term} mo`);
    lines.push(`- Monthly payment: ${usd(payment)}${budget > 0 ? (payment <= budget ? ' — fits within your monthly budget.' : ' — OVER your monthly budget; renegotiate or pick a cheaper vehicle.') : ''}`);
    lines.push(`- Total cost of loan: ${usd(totalCost(principal, apr, term))}`);
  } else {
    lines.push(NOT_COMPLETED('3'));
  }
  lines.push('');

  // Trade (Step 7)
  lines.push('## Trade-in position');
  const trade = rec(s?.trade);
  const hasTrade = !!trade && (str(trade, 'tradeValue').trim() !== '' || str(trade, 'payoff').trim() !== '');
  if (hasTrade) {
    const value = parseNumber(trade?.tradeValue);
    const payoff = parseNumber(trade?.payoff);
    const equity = value - payoff;
    lines.push(`- Trade-in value: ${usd(value)}`);
    lines.push(`- Loan payoff: ${usd(payoff)}`);
    lines.push(`- Equity: ${equity >= 0 ? '+' : ''}${usd(equity)}${equity < 0 ? ' — negative equity; avoid rolling it into the new loan.' : ''}`);
  } else {
    lines.push(NOT_COMPLETED('7'));
  }
  lines.push('');

  // Dealer-quote audit (Step 8)
  lines.push('## Dealer-quote audit');
  const fees = rec(s?.fees);
  const hasFees = !!fees && str(fees, 'docFee').trim() !== '';
  if (hasFees) {
    const docFee = parseNumber(fees?.docFee);
    lines.push(`- Documentation fee: ${usd(docFee)}`);
    lines.push(`- Title & registration: ${usd(parseNumber(fees?.titleRegistration))}`);
    const addOnList = str(fees, 'addOnsText').split(',').map((a) => a.trim()).filter(Boolean);
    if (addOnList.length > 0) lines.push(`- Add-ons quoted: ${addOnList.join(', ')}`);
    const flags = [...docFeeFlags(docFee), ...addOnFlags(addOnList)];
    if (flags.length > 0) {
      lines.push('');
      lines.push('**Red flags:**');
      for (const flag of flags) lines.push(`- ${flag.label}`);
    } else {
      lines.push('- No red flags detected in this quote.');
    }
  } else {
    lines.push(NOT_COMPLETED('8'));
  }
  lines.push('');

  // Ownership budget (Step 5)
  lines.push('## Monthly ownership budget');
  const ownership = rec(s?.ownership);
  if (ownership) {
    const keys = ['monthlyLoan', 'insurance', 'fuel', 'maintenance', 'registration', 'parking', 'taxesAndFees', 'other'];
    const values = keys.map((k) => parseNumber(ownership[k]));
    if (values.some((v) => v !== 0)) {
      lines.push(`- Estimated total per month: ${usd(values.reduce((a, b) => a + b, 0))}`);
    } else {
      lines.push(NOT_COMPLETED('5'));
    }
  } else {
    lines.push(NOT_COMPLETED('5'));
  }
  lines.push('');

  // Needs (Step 2)
  lines.push('## Non-negotiable needs');
  const vehicles = rec(s?.vehicles);
  const needs = rec(vehicles?.needs);
  const activeNeeds = needs ? Object.entries(needs).filter(([, v]) => v).map(([k]) => NEED_LABELS[k] ?? k) : [];
  if (activeNeeds.length > 0) {
    for (const label of activeNeeds) lines.push(`- ${label}`);
    const comparing = vehicles?.comparing;
    if (Array.isArray(comparing) && comparing.length > 0) {
      lines.push('');
      lines.push(`${comparing.length} vehicle${comparing.length === 1 ? '' : 's'} marked for comparison.`);
    }
  } else {
    lines.push(NOT_COMPLETED('2'));
  }
  lines.push('');

  // Deal score (Step 10)
  lines.push('## Deal score');
  const dealScore = rec(s?.dealScore);
  const result = rec(dealScore?.result);
  const score = result ? parseNumber(result.score) : 0;
  const hasScore = !!result && result.score !== undefined;
  if (hasScore) {
    lines.push(`**${score} / 100**`);
    lines.push('');
    const breakdown = Array.isArray(result.breakdown) ? (result.breakdown as { label: string; earned: number; maxPoints: number }[]) : [];
    for (const item of breakdown) lines.push(`- ${item.label}: ${item.earned}/${item.maxPoints}`);
  } else {
    lines.push(NOT_COMPLETED('10'));
  }
  lines.push('');

  lines.push('## Negotiation ground rules');
  lines.push('- Negotiate the out-the-door price first — payments last.');
  lines.push('- Get every number in writing before discussing financing.');
  lines.push('- Decline high-margin add-ons; they are optional, not required.');
  lines.push('- Walking away is your strongest move, and it costs nothing.');
  lines.push('');

  return lines.join('\n');
}
