import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

// ============================================================================
// scripts/capture-docs-dimensions.test.ts — lock the two onboarding-docs PNGs'
// dimensions to sane bounds.
//
// The gallery renders README's Handoff section and launch.md §4 to full-page
// PNGs (screenshots/docs-handoff.png, screenshots/docs-launch-gates.png) via
// capture-docs.mjs. If the renderer ever breaks — CSS collapse producing a
// tiny stub page, an empty section, a mis-resized viewport — the PNG height
// collapses toward the 800px MIN_H floor and the onboarding visuals silently
// degrade. This suite guards against that two ways:
//
//   1. The COMMITTED PNGs are parsed (pure, no Chrome, always runs): each must
//      be a real PNG whose IHDR says width 1200 and height within [2000, 6500]
//      (current renders are ~5900 and ~6050 tall — the band leaves headroom
//      for content growth while far below the 800px broken-page floor).
//   2. The FRESH renders are re-generated by re-running capture-docs.mjs into
//      a throwaway temp dir and checked against the same bounds, so a future
//      renderer change that produces a broken/tiny page is caught in CI even
//      if the committed PNGs were never re-captured. Skips-not-fails when
//      Chrome is missing (same contract as the pre-push hook's gates 3/3b),
//      so local machines without Chrome never block.
//
// The IHDR parse is dependency-free: the PNG signature is bytes 0-7, then the
// IHDR chunk carries big-endian width at bytes 16-19 and height at bytes
// 20-23 — no image library needed.
// ============================================================================

const SCRIPT = 'scripts/capture-docs.mjs';
const COMMITTED_DIR = 'screenshots';
const EXPECTED = [
  { name: 'docs-handoff.png', title: 'README Handoff' },
  { name: 'docs-launch-gates.png', title: 'launch.md §4' },
];

const WIDTH = 1200;
const MIN_HEIGHT = 2000;
// 6500 not 6000: launch.md §4 carries the Disk full emergency subsection
// (added 2026-08-08) and renders ~6050 tall; the band's real job is catching
// the 800px MIN_H broken-page collapse, so it tracks content growth while
// staying far above the floor and far below any pathological render.
const MAX_HEIGHT = 6500;

// ── Dependency-free PNG IHDR parser ─────────────────────────────────────────
// Width/height live in the IHDR chunk at fixed offsets after the 8-byte
// signature; both are big-endian uint32. Throws on a buffer that is not a PNG
// (bad signature) or is too short to hold the header.
export function readPngDimensions(buf: Buffer): { width: number; height: number } {
  const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
  if (buf.length < 24) {
    throw new Error('buffer too short to be a PNG');
  }
  for (let i = 0; i < PNG_SIGNATURE.length; i += 1) {
    if (buf[i] !== PNG_SIGNATURE[i]) {
      throw new Error('not a PNG (bad signature)');
    }
  }
  return {
    width: buf.readUInt32BE(16),
    height: buf.readUInt32BE(20),
  };
}

function assertInBounds(name: string, pngPath: string) {
  const dims = readPngDimensions(readFileSync(pngPath));
  expect(dims.width, `${name}: width must be ${WIDTH}`).toBe(WIDTH);
  expect(dims.height, `${name}: height must be within [${MIN_HEIGHT}, ${MAX_HEIGHT}]`)
    .toBeGreaterThanOrEqual(MIN_HEIGHT);
  expect(dims.height, `${name}: height must be within [${MIN_HEIGHT}, ${MAX_HEIGHT}]`)
    .toBeLessThanOrEqual(MAX_HEIGHT);
  return dims;
}

describe('scripts/capture-docs-dimensions.test.ts · onboarding-docs PNG bounds', () => {
  it('parses IHDR width/height from a real PNG buffer', () => {
    const sig = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
    const buf = Buffer.alloc(24);
    sig.copy(buf, 0);
    buf.writeUInt32BE(1200, 16);
    buf.writeUInt32BE(3724, 20);
    expect(readPngDimensions(buf)).toEqual({ width: 1200, height: 3724 });
  });

  it('rejects a non-PNG buffer', () => {
    expect(() => readPngDimensions(Buffer.from('this is not a png at all....'))).toThrow(/not a PNG/);
  });

  it('keeps the two COMMITTED PNGs within sane bounds (always runs, no Chrome)', () => {
    for (const { name, title } of EXPECTED) {
      const pngPath = join(COMMITTED_DIR, name);
      expect(existsSync(pngPath), `${pngPath} must exist (run npm run capture:docs and commit)`).toBe(true);
      // assertInBounds already enforces width === 1200 and 2000 <= height
      // <= 6000 (both > 0), so no separate non-zero guard is needed.
      assertInBounds(`${title} (${name})`, pngPath);
    }
  });
});

// ── Fresh-render check: re-run capture-docs.mjs and assert the regenerated ──
//    PNGs stay in bounds. Requires Chrome (same skip-not-fail contract as the
//    pre-push hook's Chrome-gated gates).
const CHROME = process.env.CHROME_PATH ?? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const chromeAvailable = existsSync(CHROME) && existsSync(SCRIPT);

describe.skipIf(!chromeAvailable)('fresh docs render (re-runs capture-docs.mjs)', () => {
  it('regenerates both PNGs and keeps their dimensions within sane bounds', () => {
    const outDir = mkdtempSync(join(tmpdir(), 'docs-dims-'));
    try {
      const res = spawnSync('node', [SCRIPT, '--out', outDir], {
        encoding: 'utf8',
        timeout: 120_000,
      });
      expect(res.status, `capture-docs.mjs exited ${res.status}: ${res.stderr ?? ''}`).toBe(0);
      for (const { name, title } of EXPECTED) {
        const pngPath = join(outDir, name);
        expect(existsSync(pngPath), `${title}: fresh render missing ${pngPath}`).toBe(true);
        assertInBounds(`${title} (${name}, fresh)`, pngPath);
      }
    } finally {
      rmSync(outDir, { recursive: true, force: true });
    }
  }, 120_000);
});
