// ============================================================================
// Tiny markdown-ish → HTML renderer for report emails. The engine's report
// bodies use `# / ## / - / - [ ] / - [x] / **bold** / `code``; anything richer
// stays plain text. Deliberately dependency-free.
// ============================================================================

const esc = (s: string): string =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const inline = (s: string): string =>
  esc(s)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/`(.+?)`/g, '<code>$1</code>');

const isListItem = (line: string): boolean =>
  /^- \[x\] /.test(line) || /^- \[ \] /.test(line) || /^- /.test(line) || /^\d+\. /.test(line);

export const renderReportHtml = (title: string, body: string): string => {
  const out: string[] = [];
  let inList = false;

  for (const raw of body.split('\n')) {
    const line = raw;
    const listItem = isListItem(line);

    if (listItem && !inList) {
      out.push('<ul>');
      inList = true;
    } else if (!listItem && inList) {
      out.push('</ul>');
      inList = false;
    }

    if (/^# /.test(line)) out.push(`<h1>${inline(line.slice(2))}</h1>`);
    else if (/^## /.test(line)) out.push(`<h2>${inline(line.slice(3))}</h2>`);
    else if (/^- \[x\] /.test(line)) out.push(`<li class="done">☑&nbsp; ${inline(line.slice(6))}</li>`);
    else if (/^- \[ \] /.test(line)) out.push(`<li>☐&nbsp; ${inline(line.slice(6))}</li>`);
    else if (/^- /.test(line)) out.push(`<li>${inline(line.slice(2))}</li>`);
    else if (/^\d+\. /.test(line)) out.push(`<li>${inline(line.replace(/^\d+\. /, ''))}</li>`);
    else if (line.trim() === '') out.push('');
    else out.push(`<p>${inline(line)}</p>`);
  }
  if (inList) out.push('</ul>');

  return `<!doctype html>
<html lang="en">
<head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /></head>
<body style="margin:0;padding:0;background:#FFF8E5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#FFF8E5;padding:24px 12px;">
    <tr><td align="center">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#FFFEFA;border:1px solid #F3D9A4;border-radius:16px;overflow:hidden;">
        <tr><td style="background:linear-gradient(135deg,#E94923,#D89500);padding:20px 28px;color:#fff;">
          <h1 style="margin:0;font-size:20px;font-weight:700;letter-spacing:-0.01em;">${esc(title)}</h1>
          <p style="margin:4px 0 0;font-size:12px;opacity:0.9;">App Portfolio Command Center</p>
        </td></tr>
        <tr><td style="padding:24px 28px;color:#1F2D2C;font-size:14px;line-height:1.6;">
          ${out.join('\n')}
        </td></tr>
        <tr><td style="padding:14px 28px;border-top:1px solid #F3D9A4;color:#8C9CA1;font-size:11px;">
          Generated by the Command Center automation engine. Configure delivery in
          Vercel → Settings → Environment Variables.
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
};
